// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtmZub4Zh8xfMJCPh2qlBp7fj-C3D0VXI',
    appId: '1:381279829820:web:4c76698edcccb69d84e839',
    messagingSenderId: '381279829820',
    projectId: 'final-exam-6a733',
    authDomain: 'final-exam-6a733.firebaseapp.com',
    storageBucket: 'final-exam-6a733.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhXI6484KYwWpZf7HmSZooCBW2kiUJoUs',
    appId: '1:381279829820:android:22f4330e93ed528484e839',
    messagingSenderId: '381279829820',
    projectId: 'final-exam-6a733',
    storageBucket: 'final-exam-6a733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1VLQEX4XUntc9UTJaTlC68vDsKZCYW9w',
    appId: '1:381279829820:ios:236c2f1be257bc0c84e839',
    messagingSenderId: '381279829820',
    projectId: 'final-exam-6a733',
    storageBucket: 'final-exam-6a733.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1VLQEX4XUntc9UTJaTlC68vDsKZCYW9w',
    appId: '1:381279829820:ios:236c2f1be257bc0c84e839',
    messagingSenderId: '381279829820',
    projectId: 'final-exam-6a733',
    storageBucket: 'final-exam-6a733.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtmZub4Zh8xfMJCPh2qlBp7fj-C3D0VXI',
    appId: '1:381279829820:web:fd7358fa22c2271c84e839',
    messagingSenderId: '381279829820',
    projectId: 'final-exam-6a733',
    authDomain: 'final-exam-6a733.firebaseapp.com',
    storageBucket: 'final-exam-6a733.firebasestorage.app',
  );
}
